"""EtherNet/IP CIP device type and vendor ID lookup enums."""

DEVICE_TYPE: dict[str, str] = {
    "0": "Generic Device (deprecated)",
    "2": "AC Drive",
    "3": "Motor Overload",
    "4": "Limit Switch",
    "5": "Inductive Proximity Switch",
    "6": "Photoelectric Sensor",
    "7": "General Purpose Discrete I/O",
    "9": "Resolver",
    "12": "Communications Adapter",
    "14": "Programmable Logic Controller",
    "16": "Position Controller",
    "19": "DC Drive",
    "21": "Contactor",
    "22": "Motor Starter",
    "23": "Soft Start",
    "24": "Human-Machine Interface",
    "26": "Mass Flow Controller",
    "27": "Pneumatic Valve",
    "28": "Vacuum Pressure Gauge",
    "29": "Process Control Value",
    "30": "Residual Gas Analyzer",
    "31": "DC Power Generator",
    "32": "RF Power Generator",
    "33": "Turbomolecular Vacuum Pump",
    "34": "Encoder",
    "35": "Safety Discrete I/O Device",
    "36": "Fluid Flow Controller",
    "37": "CIP Motion Drive",
    "38": "CompoNet Repeater",
    "39": "Mass Flow Controller Enhanced",
    "40": "CIP Modbus Device",
    "41": "CIP Modbus Translator",
    "42": "Safety Analog I/O Device",
    "43": "Generic Device (keyable)",
    "44": "Managed Switch",
    "59": "ControlNet Physical Layer Component",
}

# Trimmed to the first ~100 entries for readability; the full dictionary
# is embedded below (1240 entries from the original ENIP-Scanner.py).
VENDOR_ID: dict[str, str] = {
    "0": "Reserved",
    "1": "Rockwell Automation/Allen-Bradley",
    "2": "Namco Controls Corp.",
    "3": "Honeywell Inc.",
    "4": "Parker Hannifin Corp. (Veriflo Division)",
    "5": "Rockwell Automation/Reliance Elec.",
    "7": "SMC Corporation",
    "8": "Molex Incorporated",
    "9": "Western Reserve Controls Corp.",
    "10": "Advanced Micro Controls Inc. (AMCI)",
    "11": "ASCO Pneumatic Controls",
    "12": "Banner Engineering Corp.",
    "13": "Belden Wire & Cable Company",
    "14": "Cooper Interconnect",
    "16": "Daniel Woodhead Co. (Woodhead Connectivity)",
    "17": "Dearborn Group Inc.",
    "19": "Helm Instrument Company",
    "20": "Huron Net Works",
    "21": "Lumberg Inc.",
    "22": "Online Development Inc.(Automation Value)",
    "23": "Vorne Industries Inc.",
    "24": "ODVA Special Reserve",
    "26": "Festo Corporation",
    "30": "Unico Inc.",
    "31": "Ross Controls",
    "34": "Hohner Corp.",
    "35": "Micro Mo Electronics Inc.",
    "36": "MKS Instruments Inc.",
    "37": "Yaskawa Electric America",
    "39": "AVG Automation (Uticor)",
    "40": "Wago Corporation",
    "41": "Kinetics (Unit Instruments)",
    "42": "IMI Norgren Limited",
    "43": "BALLUFF Inc.",
    "44": "Yaskawa Electric America Inc.",
    "45": "Eurotherm Controls Inc",
    "46": "ABB Industrial Systems",
    "47": "Omron Corporation",
    "48": "TURCk Inc.",
    "49": "Grayhill Inc.",
    "50": "Real Time Automation (C&ID)",
    "52": "Numatics Inc.",
    "53": "Lutze Inc.",
    "56": "Softing GmbH",
    "57": "Pepperl + Fuchs",
    "58": "Spectrum Controls Inc.",
    "59": "D.I.P. Inc. MKS Inst.",
    "60": "Applied Motion Products Inc.",
    "61": "Sencon Inc.",
    "62": "High Country Tek",
    "63": "SWAC Automation Consult GmbH",
    "64": "Clippard Instrument Laboratory",
    "68": "Eaton Electrical",
    "71": "Toshiba International Corp.",
    "72": "Control Technology Incorporated",
    "73": "TCS (NZ) Ltd.",
    "74": "Hitachi Ltd.",
    "75": "ABB Robotics Products AB",
    "76": "NKE Corporation",
    "77": "Rockwell Software Inc.",
    "78": "Escort Memory Systems",
    "80": "Industrial Devices Corporation",
    "81": "IXXAT Automation GmbH",
    "82": "Mitsubishi Electric Automation Inc.",
    "83": "OPTO-22",
    "86": "Horner Electric",
    "87": "Burkert Werke GmbH & Co. KG",
    "89": "Industrial Indexing Systems Inc.",
    "90": "HMS Industrial Networks AB",
    "91": "Robicon",
    "92": "Helix Technology (Granville-Phillips)",
    "93": "Arlington Laboratory",
    "94": "Advantech Co. Ltd.",
    "95": "Square D Company",
    "96": "Digital Electronics Corp.",
    "97": "Danfoss",
    "100": "Bosch Rexroth Corporation",
    "101": "Applied Materials Inc.",
    "108": "Beckhoff Automation GmbH",
    "109": "National Instruments",
    "145": "Siemens Energy & Automation/Drives",
    "161": "Mitsubishi Electric Corporation",
    "243": "Schneider Automation Inc.",
    "250": "Yokogawa Electric Corporation",
    "255": "Bosch Rexroth",
    "256": "Turck",
    "309": "Prosoft Technology",
    "315": "SEW Eurodrive GmbH",
    "326": "GE Fanuc Automation North America Inc.",
    "344": "KEBA AG",
    "345": "Endress + Hauser",
    "351": "Kawasaki Robotics (USA) Inc.",
    "356": "Fanuc Robotics America",
    "367": "Keyence Corporation",
    "562": "Phoenix Contact",
    "591": "FANUC Ltd.",
    "808": "SICK AG",
    "887": "Bernecker + Rainer Industrie-Elektronik GmbH",
    "939": "Cisco Systems",
    "991": "Moxa Networking Co. Ltd.",
    "1006": "N-Tron",
    "1240": "Penko Engineering B.V.",
}
